version: '3.8'
services:
#  client-frontend:
#    image: frontend:0.0.1
#    build: ./frontend
#    restart: always
#    ports:
#      - '3000:3000'
#    volumes:
#      - /app/node_modules
#      - ./frontend:/app

  web-service:
    image: w_service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 6060
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/ws_order_db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20percentcooler
    ports:
      - "5432:5432"
#    volumes:
#      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
#      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db-data:
  pgadmin-data: