version: '3.8'
services:

  web-service:
    image: w_service:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 6060
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/ws_order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=20percentcooler
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20percentcooler
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: